### ISSUE TITLE
release 1.1.0: missing jars?

### ISSUE THREAD

**Issue by srenatus** [derlin/docker-compose-viz-mermaid#13]
Thank you for this wonderful project ✨ 

I was just wondering why [the latest release](https://github.com/derlin/docker-compose-viz-mermaid/releases/tag/v1.1.0) has no jar files:

<img width="331" alt="image" src="https://github.com/derlin/docker-compose-viz-mermaid/assets/870638/ada8980f-dc5a-4b04-b66b-526eebaa7ffc">

I've been using nightly instead, but I thought I'd leave a note anyways.

**Comment by derlin** [comment]
Wow, I missed that 😳, no idea what happened. Will attach them manually and see if the behavior is the same for 1.2 (will release soon). 

thank you so much for letting me know, and really happy to hear this project is helpful to you!

**Comment by srenatus** [comment]
Thanks for the quick reply and for having a look at it 😃

**Comment by derlin** [comment]
All done. Thanks again!
