### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by modem7** [derlin/docker-compose-viz-mermaid#7]
Heya,

Is there a possibility that we'll see a Docker image for this project?

Thanks!

**Comment by derlin** [comment]
I figured a jar would be as handy, but if you believe a docker image may be useful, I am happy to provide one :) 

Would you prefer a fat image with the playwright drivers included, or a slim one without the image generation support? Or both?

Let me know what you prefer, and thank you for raising the issue!

**Comment by modem7** [comment]
> I figured a jar would be as handy, but if you believe a docker image may be useful, I am happy to provide one :) 
> 
> Would you prefer a fat image with the playwright drivers included, or a slim one without the image generation support? Or both?
> 
> Let me know what you prefer, and thank you for raising the issue! 

Heya,

May be worthwhile doing both, but it depends on the workload, otherwise the fat image certainly makes sense in this case!

Thank you again!

**Comment by derlin** [comment]
Hello again! To let you know, I tried creating a docker image with Playwright inside (the browser I use to render PNG and SVG). The problem is, it is both very heavy (1.69GB!!) and very slow. It takes around 20 seconds to generate something, against a few seconds without docker. I thus wonder if this is worth it.

**Comment by modem7** [comment]
> Hello again! To let you know, I tried creating a docker image with Playwright inside (the browser I use to render PNG and SVG). The problem is, it is both very heavy (1.69GB!!) and very slow. It takes around 20 seconds to generate something, against a few seconds without docker. I thus wonder if this is worth it. 

Heya!

Thanks for trying!

If docker isn't a suitable technology, then no point spending further time on it for now! At least you can point people to this ticket if the question crops up again.

Appreciate the efforts!

**Comment by webartoli** [comment]
Hei @derlin,
  I was searching for the same docker image and I hit this issue.
  
 Maybe local renderer can be disabled for docker execution ? Or still needed for some specific usecase ?
  
 I've seen from your codebase that there are reference to several useful renderer to cover edge case:
  - kroki (local image renderer, usable via compose)
  - mermaid.ink (cloud image renderer)

In my usecase I was searching for compose.yml to mermaid text converter and a docker image can be really helpful.
